scala_library(
    name = "lib",
    srcs = glob(["*.scala"]),
    deps = [
        "@third_party//3rdparty/jvm/org/apache/commons:commons_text",
    ],
    exports = [
        "@third_party//3rdparty/jvm/org/apache/commons:commons_text",
    ],
    visibility = ["//hcl4s:__subpackages__"]
)