
scala_binary(
    name = "parse-test",
    srcs = ["TestParse.scala"],
    deps = [
        "//hcl4s/parser:lib",
        "@third_party//3rdparty/jvm/com/lihaoyi:pprint",
    ],
    main_class = "dev.jtrim777.hcl4s.TestParse",
)