
scala_library(
    name = "lib",
    srcs = glob(["**/*.scala"]),
    deps = [
        "//hcl4s/lang:lib",
        "//hcl4s/model:lib",
        "@third_party//3rdparty/jvm/com/chuusai:shapeless",
    ],
    exports = [
        "//hcl4s/lang:lib",
        "//hcl4s/model:lib",
        "@third_party//3rdparty/jvm/com/chuusai:shapeless",
    ],
)